# Generated by Django 5.2.16 on 2026-09-26 23:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalAcceptance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        choices=[
                            ("terms", "Términos y condiciones"),
                            ("privacy", "Política de privacidad"),
                        ],
                        max_length=10,
                        verbose_name="documento",
                    ),
                ),
                ("version", models.CharField(max_length=40, verbose_name="versión")),
                (
                    "accepted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="aceptado en"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="navegador"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_acceptances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "aceptación",
                "verbose_name_plural": "aceptaciones",
                "db_table": "legal_acceptance",
                "ordering": ["-accepted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "document", "version"),
                        name="legal_one_acceptance_per_version",
                    )
                ],
            },
        ),
    ]
