# Generated by Django 5.2.16 on 2026-07-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("cash", "Efectivo"), ("transfer", "Transferencia")],
                default="cash",
                max_length=12,
                verbose_name="método de pago",
            ),
        ),
    ]
