# Generated by Django 5.2.16 on 2026-09-24 20:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0004_alter_tariff_options_alter_tariff_in_catalog"),
        ("projects", "0003_progress_labor_unit_price"),
        ("quotes", "0004_quote_document_is_not_a_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("person", "Persona"), ("company", "Empresa")],
                        default="person",
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="correo"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="notas"),
                ),
                (
                    "is_self",
                    models.BooleanField(
                        default=False,
                        help_text="El propio despacho. Se le reparte trabajo para saber qué parte hace, pero no se le debe ni se le paga.",
                        verbose_name="soy yo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "personal",
                "verbose_name_plural": "personal",
                "db_table": "staff_worker",
                "ordering": ["-is_self", "name"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="cantidad repartida",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="precio unitario que se le paga",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="nota"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="projects.project",
                        verbose_name="proyecto",
                    ),
                ),
                (
                    "quote_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="quotes.quoteitem",
                        verbose_name="partida",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="staff.worker",
                        verbose_name="personal",
                    ),
                ),
            ],
            options={
                "verbose_name": "reparto",
                "verbose_name_plural": "repartos",
                "db_table": "staff_assignment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkerPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="monto"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("cash", "Efectivo"), ("transfer", "Transferencia")],
                        default="cash",
                        max_length=12,
                        verbose_name="método de pago",
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="nota"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propietario",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worker_payments",
                        to="projects.project",
                        verbose_name="proyecto",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="staff.worker",
                        verbose_name="personal",
                    ),
                ),
            ],
            options={
                "verbose_name": "pago a personal",
                "verbose_name_plural": "pagos a personal",
                "db_table": "staff_workerpayment",
                "ordering": ["date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkerService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vacío: se acuerda al repartir el trabajo.",
                        max_digits=12,
                        null=True,
                        verbose_name="precio unitario que se le paga",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_services",
                        to="catalog.tariff",
                        verbose_name="servicio",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="staff.worker",
                        verbose_name="personal",
                    ),
                ),
            ],
            options={
                "verbose_name": "servicio del personal",
                "verbose_name_plural": "servicios del personal",
                "db_table": "staff_workerservice",
                "ordering": ["tariff__name"],
            },
        ),
        migrations.AddIndex(
            model_name="worker",
            index=models.Index(
                fields=["owner", "name"], name="staff_worke_owner_i_2e2917_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="worker",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_self", True)),
                fields=("owner",),
                name="staff_one_self_per_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("quote_item", "worker"), name="staff_one_share_per_item_worker"
            ),
        ),
        migrations.AddConstraint(
            model_name="workerservice",
            constraint=models.UniqueConstraint(
                fields=("worker", "tariff"), name="staff_service_once_per_worker"
            ),
        ),
    ]
