# Generated by Django 5.2.16 on 2026-09-24 18:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                ("document", models.JSONField(verbose_name="documento")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "plano",
                "verbose_name_plural": "planos",
                "db_table": "planner_plan",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-updated_at"],
                        name="planner_pla_owner_i_79f141_idx",
                    )
                ],
            },
        ),
    ]
