# Generated by Django 5.2.16 on 2026-07-23 12:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("quotes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="cantidad avanzada",
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "quote_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progresses",
                        to="quotes.quoteitem",
                        verbose_name="partida",
                    ),
                ),
            ],
            options={
                "verbose_name": "avance",
                "verbose_name_plural": "avances",
                "db_table": "projects_progress",
                "ordering": ["date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="evidence/", verbose_name="imagen"),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="projects.progress",
                        verbose_name="avance",
                    ),
                ),
            ],
            options={
                "verbose_name": "evidencia",
                "verbose_name_plural": "evidencias",
                "db_table": "projects_evidence",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "En curso"),
                            ("finished", "Finalizado"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propietario",
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project",
                        to="quotes.quote",
                        verbose_name="cotización",
                    ),
                ),
            ],
            options={
                "verbose_name": "proyecto",
                "verbose_name_plural": "proyectos",
                "db_table": "projects_project",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="progress",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progresses",
                to="projects.project",
                verbose_name="proyecto",
            ),
        ),
    ]
