# Generated by Django 5.2.16 on 2026-07-23 17:51

from django.db import migrations, models

import common.uploads


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="image",
            field=models.ImageField(
                upload_to=common.uploads.evidence_upload_to, verbose_name="imagen"
            ),
        ),
    ]
