# Generated by Django 5.2.16 on 2026-09-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_evidence_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="labor_unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Lo que se le paga a quien lo hizo, copiado del reparto. Se guarda aquí para que cambiar un trato de hoy no reescriba lo ya trabajado.",
                max_digits=12,
                null=True,
                verbose_name="precio unitario de mano de obra",
            ),
        ),
    ]
