# Generated by Django 5.2.16 on 2026-09-24 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_progress_labor_unit_price"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="progresses",
                to="staff.worker",
                verbose_name="quién lo hizo",
            ),
        ),
    ]
