# Generated by Django 5.2.16 on 2026-09-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_tariff_options_alter_tariff_in_catalog"),
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quoteitem",
            options={
                "ordering": ["created_at"],
                "verbose_name": "servicio cotizado",
                "verbose_name_plural": "servicios cotizados",
            },
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="tariff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote_items",
                to="catalog.tariff",
                verbose_name="servicio",
            ),
        ),
    ]
