# Generated by Django 5.2.16 on 2026-09-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_alter_quoteitem_options_alter_quoteitem_tariff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quoteitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Hasta seis decimales: un total acordado no siempre se reparte en centavos entre la cantidad.",
                max_digits=16,
                verbose_name="precio unitario",
            ),
        ),
    ]
