# Generated by Django 5.2.16 on 2026-09-26 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0004_quote_document_is_not_a_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="notes",
            field=models.TextField(
                blank=True, default="", max_length=2000, verbose_name="observaciones"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="validity_days",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Cuántos días valen los precios desde la fecha de emisión.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
                verbose_name="días de vigencia",
            ),
        ),
    ]
