# Generated by Django 5.2.16 on 2026-10-09 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0002_photo_conversion"),
        ("quotes", "0005_observaciones_y_vigencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="planner.plan",
                verbose_name="plano",
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="from_plan",
            field=models.BooleanField(default=False, verbose_name="viene del plano"),
        ),
    ]
