# Generated by Django 5.2.16 on 2026-09-18 05:09

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre que llevan los documentos; vacío los firma presuplano.",
                        max_length=120,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#1E56D6",
                        help_text="Color hexadecimal del encabezado de los documentos.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El color debe ser hexadecimal, por ejemplo #1E56D6.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="color",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "organización",
                "verbose_name_plural": "organizaciones",
                "db_table": "account_organization",
            },
        ),
    ]
