# Generated by Django 5.2.16 on 2026-09-25 01:03

from django.db import migrations, models

import common.uploads


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_organization_for_existing_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="La imagen que llevan los documentos junto al nombre.",
                null=True,
                upload_to=common.uploads.organization_logo_upload_to,
                verbose_name="logotipo",
            ),
        ),
    ]
