# Generated by Django 5.2.16 on 2026-09-25 05:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_organization_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="correo",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="correo verificado"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="teléfono",
            ),
        ),
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("signup", "Verificación de la cuenta"),
                            ("password_reset", "Cambio de contraseña"),
                        ],
                        max_length=20,
                        verbose_name="motivo",
                    ),
                ),
                ("code_hash", models.CharField(max_length=128, verbose_name="código")),
                ("expires_at", models.DateTimeField(verbose_name="vence en")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="usado en"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "código de verificación",
                "verbose_name_plural": "códigos de verificación",
                "db_table": "account_otpcode",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "-created_at"],
                        name="account_otp_user_id_f8bfe2_idx",
                    )
                ],
            },
        ),
    ]
