# Generated by Django 5.2.16 on 2026-09-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_email_como_identidad_y_contacto_de_la_organizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="correo por confirmar",
            ),
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("signup", "Verificación de la cuenta"),
                    ("password_reset", "Cambio de contraseña"),
                    ("email_change", "Cambio de correo"),
                ],
                max_length=20,
                verbose_name="motivo",
            ),
        ),
    ]
