# Generated by Django 5.2.16 on 2026-09-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_correo_por_confirmar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre que llevan los documentos; vacío los firma CUOTREKA.",
                max_length=120,
                verbose_name="nombre",
            ),
        ),
    ]
