# Generated by Django 5.2.16 on 2026-07-23 12:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "db_table": "clients_client",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "name"], name="clients_cli_owner_i_ae608d_idx"
                    )
                ],
            },
        ),
    ]
