# Generated by Django 5.2.16 on 2026-09-25 01:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.uploads


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("texture", "Textura"), ("model", "Mobiliario")],
                        default="texture",
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Cómo lo nombra el plano: la misma con la que se vuelve a pedir.",
                        max_length=400,
                        verbose_name="ruta",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=common.uploads.plan_asset_upload_to,
                        verbose_name="archivo",
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tamaño en bytes"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "archivo del editor",
                "verbose_name_plural": "archivos del editor",
                "db_table": "assets_planasset",
                "ordering": ["path"],
                "indexes": [
                    models.Index(
                        fields=["owner", "kind"], name="assets_plan_owner_i_932798_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "path"), name="assets_one_file_per_path"
                    )
                ],
            },
        ),
    ]
