# Generated by Django 5.2.16 on 2026-09-25 05:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="El id con el que el plano nombra al mueble.",
                        max_length=200,
                        verbose_name="id del modelo",
                    ),
                ),
                ("fiche", models.JSONField(verbose_name="ficha")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_models",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "modelo del catálogo",
                "verbose_name_plural": "modelos del catálogo",
                "db_table": "assets_catalogmodel",
                "ordering": ["model_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "model_id"), name="assets_one_model_per_id"
                    )
                ],
            },
        ),
    ]
