# Generated by Django 5.2.16 on 2026-07-23 12:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("square_meter", "Metro cuadrado"),
                            ("linear_meter", "Metro lineal"),
                            ("floor_wall", "Piso/Muro"),
                            ("unit", "Unidad"),
                        ],
                        default="square_meter",
                        max_length=20,
                        verbose_name="tipo de unidad",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="precio unitario"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propietario",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarifa",
                "verbose_name_plural": "tarifas",
                "db_table": "catalog_tariff",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "name"], name="catalog_tar_owner_i_fad8c6_idx"
                    )
                ],
            },
        ),
    ]
