# Generated by Django 5.2.16 on 2026-07-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="descripción"),
        ),
    ]
