# Generated by Django 5.2.16 on 2026-07-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_tariff_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="in_catalog",
            field=models.BooleanField(
                default=True,
                help_text="Si es falso, la tarifa es única de una cotización.",
                verbose_name="en catálogo",
            ),
        ),
    ]
