# Generated by Django 5.2.16 on 2026-09-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_tariff_in_catalog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tariff",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "servicio",
                "verbose_name_plural": "servicios",
            },
        ),
        migrations.AlterField(
            model_name="tariff",
            name="in_catalog",
            field=models.BooleanField(
                default=True,
                help_text="Si es falso, el servicio es único de una cotización.",
                verbose_name="en catálogo",
            ),
        ),
    ]
