# Generated by Django 5.2.16 on 2026-09-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_tariff_options_alter_tariff_in_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tariff",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("square_meter", "Metro cuadrado"),
                    ("linear_meter", "Metro lineal"),
                    ("floor_wall", "Piso/Muro"),
                    ("unit", "Por lote (único)"),
                ],
                default="square_meter",
                max_length=20,
                verbose_name="tipo de unidad",
            ),
        ),
    ]
