# Generated by Django 5.2.16 on 2026-09-19 05:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="mensaje"
                    ),
                ),
                (
                    "handled",
                    models.BooleanField(default=False, verbose_name="atendido"),
                ),
            ],
            options={
                "verbose_name": "contacto",
                "verbose_name_plural": "contactos",
                "db_table": "leads_lead",
                "ordering": ["-created_at"],
            },
        ),
    ]
